apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  .env: |-
    # -*- coding: utf-8 -*-
    # Flask Server
    DEBUG = {{ .Values.service.debug }}
    HOST = {{ .Values.service.host }}
    PORT = {{ .Values.service.targetPort }}
    FLASK_ENV = {{ .Values.service.flaskEnv }}
    SECRET_KEY = {{ .Values.service.secretKey }}
    URL_PREFIX = {{ .Values.service.urlPrefix }}
    
    # Logging conf
    SQLALCHEMY_DATABASE_URI = {{ .Values.database.uri }}
    SQLALCHEMY_TRACK_MODIFICATIONS = {{ .Values.database.notifications }}
    
    # Logging conf
    FORMAT = {{ .Values.logging.format }}
    LOG_FILE = {{ .Values.logging.logFile }}
    MAX_BYTES = {{ .Values.logging.maxBytes }}
    BACKUP_LOGS = {{ .Values.logging.backupLogs }}
