apiVersion: v1
kind: Service
metadata:
  name: {{ include "people.fullname" . }}
  labels:
    {{- include "people.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "people.selectorLabels" . | nindent 4 }}
